apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-backend-spotifyapi
spec:
  replicas: 5
  selector:
    matchLabels:
      app: streamwizard-backend-spotifyapi
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled  # This annotation enables automatic injection
      labels:
        app: streamwizard-backend-spotifyapi
    spec:
      containers:
        - name: streamwizard-backend-spotifyapi
          image: ghcr.io/streamerbuddybot/spotifyapi:a2f2593e7409aee7998f70495c8af66983c6e721
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: streamwizard-backend
          volumeMounts:
            - name: grpc-dns
              mountPath: /usr/src/app/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: grpc-dns
          configMap:
            name: grpc-dns
